// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppgflxqfjnfmntboxzpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ2ZseHFmam5mbW50Ym94enB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODU3NTEsImV4cCI6MjA2MDA2MTc1MX0.tQHoZwWX4cJmy1XUc4Q1AJ5iaIvb4eBb75bX3PZkAQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);